src/Entity/Etablisement.php
<?php

namespace App\Entity;

use App\Repository\EtablisementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EtablisementRepository::class)
 */
class Etablisement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $postalcode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_contact;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note;

    /**
     * @ORM\OneToMany(targetEntity=Prestation::class, mappedBy="etablisement")
     */
    private $prestation;

    public function __construct()
    {
        $this->prestation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalcode(): ?int
    {
        return $this->postalcode;
    }

    public function setPostalcode(int $postalcode): self
    {
        $this->postalcode = $postalcode;

        return $this;
    }

    public function getNameContact(): ?string
    {
        return $this->name_contact;
    }

    public function setNameContact(string $name_contact): self
    {
        $this->name_contact = $name_contact;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Prestation[]
     */
    public function getPrestation(): Collection
    {
        return $this->prestation;
    }

    public function addPrestation(Prestation $prestation): self
    {
        if (!$this->prestation->contains($prestation)) {
            $this->prestation[] = $prestation;
            $prestation->setEtablisement($this);
        }

        return $this;
    }

    public function removePrestation(Prestation $prestation): self
    {
        if ($this->prestation->removeElement($prestation)) {
            // set the owning side to null (unless already changed)
            if ($prestation->getEtablisement() === $this) {
                $prestation->setEtablisement(null);
            }
        }

        return $this;
    }
}

src/Form/EtablisementType.php
<?php

namespace App\Form;

use App\Entity\Etablissement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtablisementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('adress')
            ->add('city')
            ->add('postalcode')
            ->add('name_contact')
            ->add('phone')
            ->add('email')
            ->add('note')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etablissement::class,
        ]);
    }
}

src/Controller/EtablisementController.php
<?php

namespace App\Controller;

use App\Entity\Etablisement;
use App\Form\EtablisementType;
use App\Repository\EtablisementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/etablisement")
 * @IsGranted("ROLE_USER")
 */
class EtablisementController extends AbstractController
{
    /**
     * @Route("/", name="etablisement_index", methods={"GET"})
     */
    public function index(EtablisementRepository $etablisementRepository): Response
    {
        return $this->render('etablisement/index.html.twig', [
            'etablisements' => $etablisementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="etablisement_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $etablisement = new Etablisement();
        $form = $this->createForm(EtablisementType::class, $etablisement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($etablisement);
            $entityManager->flush();

            return $this->redirectToRoute('etablisement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etablisement/new.html.twig', [
            'etablisement' => $etablisement,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="etablisement_show", methods={"GET"})
     */
    public function show(Etablisement $etablisement): Response
    {
        return $this->render('etablisement/show.html.twig', [
            'etablisement' => $etablisement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="etablisement_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Etablisement $etablisement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EtablisementType::class, $etablisement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('etablisement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etablisement/edit.html.twig', [
            'etablisement' => $etablisement,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="etablisement_delete", methods={"POST"})
     */
    public function delete(Request $request, Etablisement $etablisement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etablisement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($etablisement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('etablisement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/etablisement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Etablisement{% endblock %}

{% block body %}
    <h1>Edit Etablisement</h1>

    {{ include('etablisement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('etablisement_index') }}">back to list</a>

    {{ include('etablisement/_delete_form.html.twig') }}
{% endblock %}

templates/etablisement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etablisement index{% endblock %}

{% block body %}
    <h1>Etablisement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Adress</th>
                <th>City</th>
                <th>Postalcode</th>
                <th>Name_contact</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Note</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etablisement in etablisements %}
            <tr>
                <td>{{ etablisement.id }}</td>
                <td>{{ etablisement.name }}</td>
                <td>{{ etablisement.adress }}</td>
                <td>{{ etablisement.city }}</td>
                <td>{{ etablisement.postalcode }}</td>
                <td>{{ etablisement.nameContact }}</td>
                <td>{{ etablisement.phone }}</td>
                <td>{{ etablisement.email }}</td>
                <td>{{ etablisement.note }}</td>
                <td>
                    <a href="{{ path('etablisement_show', {'id': etablisement.id}) }}">show</a>
                    <a href="{{ path('etablisement_edit', {'id': etablisement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('etablisement_new') }}">Create new</a>
{% endblock %}

templates/etablisement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etablisement{% endblock %}

{% block body %}
    <h1>Etablisement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etablisement.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ etablisement.name }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ etablisement.adress }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ etablisement.city }}</td>
            </tr>
            <tr>
                <th>Postalcode</th>
                <td>{{ etablisement.postalcode }}</td>
            </tr>
            <tr>
                <th>Name_contact</th>
                <td>{{ etablisement.nameContact }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ etablisement.phone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ etablisement.email }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ etablisement.note }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('etablisement_index') }}">back to list</a>

    <a href="{{ path('etablisement_edit', {'id': etablisement.id}) }}">edit</a>

    {{ include('etablisement/_delete_form.html.twig') }}
{% endblock %}