src/Entity/Prestation.php
<?php

namespace App\Entity;

use App\Repository\PrestationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PrestationRepository::class)]
class Prestation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    #[Assert\NotBlank(message: 'Le prix  est obligatoire.')]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: 'Le mode de paiement est obligatoire.')]
    private string $paymentmethod;

    #[ORM\Column(type: 'string')]
    private Bool $paymentstatus;

    #[ORM\Column(type: 'text', nullable: true)]
    private $reference;

    #[ORM\ManyToOne(targetEntity: Etablissement::class, inversedBy: 'prestation')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank(message: "L'établissement' est obligatoire.")]
    private $etablissement;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: 'Le type de prestation est obligatoire.')]
    private $type;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startTime = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endTime = null;

    #[ORM\Column(length: 255)]
    private ?string $color = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPaymentMethod(): ?string
    {
        return $this->paymentmethod;
    }

    public function setPaymentMethod(string $paymentmethod): self
    {
        $this->paymentmethod = $paymentmethod;

        return $this;
    }

    public function getPaymentStatus(): ?string
    {
        return $this->paymentstatus;
    }

    public function setPaymentStatus(string $paymentstatus): self
    {
        $this->paymentstatus = $paymentstatus;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getEtablissement(): ?Etablissement
    {
        return $this->etablissement;
    }

    public function setEtablissement(?Etablissement $etablissement): self
    {
        $this->etablissement = $etablissement;

        return $this;
    }

    public function __toString() {
        return $this->payment_methods;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->endTime;
    }

    public function setEndTime(\DateTimeInterface $endTime): self
    {
        $this->endTime = $endTime;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }
}

templates/pdf/invoice.html.twig
<h1 style="text-align: center; text-decoration: underline">Facture {{ prestation.id }}</h1>
<h2 style=" text-align:center; text-decoration: underline;">Entre les soussignés</h2>
<h3 style="text-decoration: underline">Prestataire :</h3>
<p>Nom Prénom : <span style="font-weight: bold">{{ user.lastname }} {{ user.firstname }}</span></p>
<p>Adresse : <span style="font-weight: bold">{{ user.adress }} {{ user.postalcode }} {{ user.city }}</span></p>
<p>Téléphone : <span style="font-weight: bold">{{ user.phone }}</span></p>

<h3 style="text-decoration: underline">Organisateur :</h3>
<p>Nom prénom : <span style="font-weight: bold">{{ prestation.etablissement.name }}</span></p>
<p>Adresse : <span style="font-weight: bold">{{ prestation.etablissement.adress }} {{ prestation.etablissement.postalcode }} {{ prestation.etablissement.city }}</span></p>
<p>Téléphone : <span style="font-weight: bold">{{ prestation.etablissement.phone }}</span></p>
<p>Adresse mail : <span style="font-weight: bold">{{ prestation.etablissement.email }}</span></p>

<h3 style="text-decoration: underline">Prestation :</h3>
<p style="text-decoration: underline">{{ prestation.type }}</p>
<p>{{ prestation.date|date("d/m/Y") }}</p>
<p>Horaire : de {{ prestation.startTime }} à {{ prestation.endTime }} (horaires facultatif suivant l'organisateur)</p>
<p>Lieu : {{ prestation.etablissement.city }}</p>

<h3 style="text-decoration: underline">Rémunération :</h3>
<p>Il a été convenu un tarif forfaitaire de <span style="font-weight: bold">{{ prestation.price }}</span> € TTC pour les frais de déplacement.</p>
<p>Mode de réglement : {{ prestation.paymentMethod }}</p>

<p style="text-align: center">Fait en deux exemplaires à {{ prestation.etablissement.city }} le {{ prestation.date|date("d/m/Y") }}</p>

<div style="display: flex; justify-content: space-around">
    <p style="text-decoration: underline; margin-bottom: 10rem">Le prestataire</p>
    <p style="text-decoration: underline;">L’organisateur</p>
</div>